apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundhub-client
spec:
  selector:
    matchLabels:
      app: fundhub-client
  replicas: 1
  template:
    metadata:
      labels:
        app: fundhub-client
        version: "1.0"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: fundhub-client
          image: titan29/fundhub-client:1
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "10m"
          ports:
            - containerPort: 3010
          envFrom:
            - configMapRef:
                name: fundhub-client-config
