apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-fundhub-client
spec:
  hosts:
    - "fundhub-client-svc.frontend.svc.cluster.local"
  http:
    - name: "fundhub-canary-deployment"
      route:
        - destination:
            host: fundhub-client-svc.frontend.svc.cluster.local
            subset: v1
          weight: 40
        - destination:
            host: fundhub-client-svc.frontend.svc.cluster.local
            subset: v2
          weight: 60