apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundhub-api-v2
spec:
  selector:
    matchLabels:
      app: fundhub-api
  replicas: 1
  template:
    metadata:
      labels:
        app: fundhub-api
        version: "2.0"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: fundhub-api
          image: titan29/fundhub-api:2
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "32Mi"
              cpu: "10m"
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: DB_PORT
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: PORT
            - name: SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: SERVER_KEY
            - name: CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: CLIENT_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fundhub-api-secret
                  key: SECRET_KEY
