apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - destinationrule.yaml
  - virtual-service.yaml
  - deployment-v2.yaml
  # - hpa.yaml

generatorOptions:
  disableNameSuffixHash: true