apiVersion: v1
kind: Secret
metadata:
  name: sops-age
type: Opaque
data:
  age.agekey: IyBwdWJsaWMga2V5OiBhZ2UxOXFxbHpwZ3Nkenhmc3lua2NhbWFjOWNwd3VwNXgwOHQ1MzdwazZnemx2cTM4ajU5MmZyczc4eTBuegpBR0UtU0VDUkVULUtFWS0xWEhWTVFRQzJRN005RzQ5VVBWTE5HV1g2TTg4SDdLNDhMVTA0VjU3OVpNTVVORDZEVFo3U01DUkxKMA==